[build]
buildCommand = "npm install && npm run build && npm --prefix server install && npm --prefix server run build"

[deploy]
startCommand = "npm --prefix server run migrate && node server/dist/app.js"
